cat_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('cats/', views.cats_index, name = 'cats_index'),
    path('cats/<int:cat_id>', views.cats_show, name = 'cats_show'),
    path('cats/create/', views.CatCreate.as_view(), name = 'cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name = 'cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name = 'cats_delete'),
    path('user/<username>/', views.profile, name = 'profile'),
    path('cattoys/', views.cattoys_index, name = 'cattoys_index'),
    path('cattoys/<int:cattoy_id>', views.cattoys_show, name = 'cattoys_show'),
    path('cattoys/create/', views.CatToyCreate.as_view(), name = 'cattoys_create'),
    path('cattoys/<int:pk>/update/', views.CatToyUpdate.as_view(), name = 'cattoys_update'),
    path('cattoys/<int:pk>/delete/', views.CatToyDelete.as_view(), name = 'cattoys_delete'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('signup/', views.signup_view, name = 'signup')
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CatToy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cattoys = models.ManyToManyField(CatToy)
    
    def __str__(self):
        return self.name

main_app/views.py
from django.shortcuts import render
from .models import Cat, CatToy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# MAIN ----------------
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

# USER ----------------
@login_required
def profile(request, username):
    user = User.objects.get(username = username)
    cats = Cat.objects.filter(user = user)
    return render(request, 'profile.html', {
        'username': username,
        'cats': cats
    })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/' + username)
                else:
                    print(f'The account for {username} has been disabled.')
            else:
                print('The username and/or password is incorrect.')
        else:
            form = AuthenticationForm()
            return render(request, 'login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/cats')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect('/user/' + str(user))
        else:
            form = UserCreationForm()
            return render(request, 'signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

# CATS ----------------
def cats_index(request):
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})

def cats_show(request, cat_id):
    cat = Cat.objects.get(id = cat_id)
    return render(request, 'cats/show.html', {'cat': cat})

@method_decorator(login_required, name = 'dispatch')
class CatCreate(CreateView):
    model = Cat
    fields = '__all__'
    success_url = '/cats'

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/cats/' + str(self.object.pk))

@method_decorator(login_required, name = 'dispatch')
class CatUpdate(UpdateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age', 'cattoys']
    
    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.save()
        return HttpResponseRedirect('/cats')

@method_decorator(login_required, name = 'dispatch')
class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats'

# CATTOYS ----------------
def cattoys_index(request):
    cattoys = CatToy.objects.all()
    return render(request, 'cattoys/index.html', {'cattoys': cattoys})

def cattoys_show(request, cattoy_id):
    cattoy = CatToy.objects.get(id = cattoy_id)
    return render(request, 'cattoys/show.html', {'cattoy': cattoy})

@method_decorator(login_required, name = 'dispatch')
class CatToyCreate(CreateView):
    model = CatToy
    fields = '__all__'
    success_url = '/cattoys'

@method_decorator(login_required, name = 'dispatch')
class CatToyUpdate(UpdateView):
    model = CatToy
    fields = ['name', 'color']
    success_url = '/cattoys'

@method_decorator(login_required, name = 'dispatch')
class CatToyDelete(DeleteView):
    model = CatToy
    success_url = '/cattoys'

main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>About the Cat Collector</title>
    </head>
    <body>
        <h1>About the Cat Collector</h1>
        <hr />
        <p>Hire the catcollector!</p>
        <footer>All Rights Reserved, CatCollector 2021</footer>
    </body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <title>Cat Collector</title>
    </head>
    <body>
        <header>
            {% if user.is_authenticated %}
                <span><a href='{% url 'profile' user.username %}'>Hello, {{user.username}}</a></span> |
                <span><a href='{% url 'logout' %}'>Logout</a></span>
            {% else %}
                <span><a href='{% url 'login' %}'>Login</a></span> |
                <span><a href='{% url 'signup' %}'>Signup</a></span>
            {% endif %}
            
            <a href="/cats">
                <h1>Cat Collector</h1>
            </a>
        </header>

        {% block content %}
        {% endblock %}

        <footer>All rights reserverd, Cat Collector 2021</footer>
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    </body>
</html>

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <a href='/cats/create'>Add a New Cat</a>
    {% endif %}
    <hr>
    {% for cat in cats %}
        <a href="/cats/{{ cat.id }}">
            <p>Name: {{ cat.name }}</p>
        </a>
        <a href="/user/{{ cat.user.username }}">
            <p>Adopted By: {{ cat.user.username }}</p>
        </a>
        {% if cat.age > 0 %}
            <p>Age: {{ cat.age }}</p>
        {% else %}
            <p>Age: Kitten</p>
        {% endif %}
        <hr />
    {% endfor %}
{% endblock %}

main_app/templates/cats/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='card-body'>
        <h1 class='card-title'>Name: {{ cat.name }}</h1>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
            <p>Age: {{cat.age}}</p>
        {% else %}
            <p>Age: Kitten</p>
        {% endif %}
        <p>Toys:</p>
        {% for cattoy in cat.cattoys.all %}
            <p>{{cattoy.name}}</p>
        {% empty %}
            <p>Cat has no toys...</p>
        {% endfor %}
        {% if user.is_authenticated %}
            <a 
                class='btn btn-primary' 
                href='{% url 'cats_update' cat.id %}'
            >
                Update Details
            </a>
            <a 
                class='btn btn-danger' 
                href='{% url 'cats_delete' cat.id %}'
            >
                Delete Cat
            </a>
        {% endif %}
    </div>
{% endblock %}

main_app/templates/cattoys/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Cat Toy List</h1>
    {% if user.is_authenticated %}
        <a href='/cattoys/create'>Add a New Cat Toy</a>
    {% endif %}
    <hr>
    {% for cattoy in cattoys %}
        <div>
            <a href='{% url 'cattoys_show' cattoy.id %}'>
                <div class='card-content'>
                    <p>{{cattoy.name}}</p>
                    <p>{{cattoy.color}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

main_app/templates/cattoys/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class='card-body'>
        <h1>Cat Toy Details</h1>
        <h2 class='card-title'>Name: {{ cattoy.name }}</h2>
        <p>Color: {{ cattoy.color }}</p>
        <p>Owners:</p>
        {% for cat in cattoy.cat_set.all %}
            <p>{{cat.name}}</p>
        {% empty %}
            <p>No cat has this toy...</p>
        {% endfor %}
        {% if user.is_authenticated %}
            <a 
                class='btn btn-primary' 
                href='{% url 'cattoys_update' cattoy.id %}'
            >
                Update Toy Details
            </a>
            <a 
                class='btn btn-danger' 
                href='{% url 'cattoys_delete' cattoy.id %}'
            >
                Delete Toy
            </a>
        {% endif %}
    </div>
{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    <form action='.' method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input class='btn btn-primary' type='submit' value='Submit'>
    </form>
{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Cat</h1>
    <p>Are you sure you want to delete {{ cat }}?</p>
    <form action='' method='post'>
        {% csrf_token %}
        <input type='submit' value='Delete'>
    </form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}

{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type='submit' value='Submit'>
    </form>
{% endblock %}

main_app/templates/main_app/cattoy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Cat Toy</h1>
    <p>Are you sure you want to delete <strong>{{ cattoy }}</strong>?</p>
    <form action='' method='post'>
        {% csrf_token %}
        <input class='btn btn-danger' type='submit' value='Delete'>
        <a class='btn btn-secondary' href='{% url 'cattoys_show' cattoy.id %}'>Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/cattoy_form.html
{% extends 'base.html' %}

{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input class='btn btn-success' type='submit' value='Submit'>
    </form>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>{{username}}'s Cat Collection</h1>
    {% for cat in cats %}
        <a href='/cats/{{cat.id}}'>
            <p>Name: {{cat.name}}</p>
        </a>
    {% endfor %}
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Signup</h1>
    <form action='.' method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input class='btn btn-success' type='submit' value='Sign Up'>
    </form>
{% endblock %}